#!/bin/bash

declare -g opt
declare -g file

function usage {
    cat<<EOF>&2
Synopsis

  $0 ?

  $0 -n file

Description

  Print ORDINAL of filename, e.g., "0" in "name-0.txt".

  The ordinal is known as a single digit in a hyphenated sequence.

EOF
}

function filename {
    for tok in $(echo ${file} | sed 's%-% %g')
    do
        if [ -n "$(echo ${tok} | egrep '^[0-9]$')" ]
        then
            echo ${tok}
            return 0
        fi
    done
    return 1
}
#
#
#
if [ -n "${1}" ]&&[ -n "${2}" ]
then
    opt="${1}"
    file="${2}"
    
    case "${opt}" in

        -n)
            if filename "${file}"
            then
                exit 0
            else
                exit 1
            fi
        ;;
    esac
else
    usage
fi
